In [2]:
import sys
sys.path.append("../../eventepi")

import numpy as np
import pandas as pd
from itertools import product
from sklearn.model_selection import train_test_split

from eventepi.classification import DataLoader

X, y = DataLoader().labeled_texts()
X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.25, random_state=13353)

X_d, y_d = DataLoader().labeled_date_sentences()
X_tr_d, X_te_d, y_tr_d, y_te_d = train_test_split(X_d, y_d, test_size=0.25, random_state=13353)

X_c, y_c = DataLoader().labeled_count_sentences()
X_tr_c, X_te_c, y_tr_c, y_te_c = train_test_split(X_c, y_c, test_size=0.25, random_state=13353)

Create labeled sentences: 100%|██████████| 53/53 [01:20<00:00,  1.51s/it]
Create labeled sentences: 100%|██████████| 112/112 [02:43<00:00,  1.46s/it]

In [3]:
train, validate, test = np.split(np.array(range(len(X))), [int(.6*len(X)), int(.8*len(X))], )

set_sizes = pd.DataFrame(product(["positive", "negative"], 
                     ["relevance_scoring", "key_date_extraction", "key_count_extraction", "relevance_scoring_CNN"], 
                     ["train", "test", "validation"]),
             columns=["class", "task", "data_set"]
            )
size = [sum(y_tr), 
        sum(y_te), 
        None, 
        sum(y_tr_d),
        sum(y_te_d),
        None,
        sum(y_tr_c),
        sum(y_te_c),
        None,
        sum(np.array(y)[train]),
        sum(np.array(y)[test]),
        sum(np.array(y)[validate]),
        len(y_tr) - sum(y_tr), 
        len(y_te) - sum(y_te), 
        None, 
        len(y_tr_d) - sum(y_tr_d),
        len(y_te_d) - sum(y_te_d),
        None,
        len(y_tr_c) - sum(y_tr_c),
        len(y_te_c) - sum(y_te_c),
        None,
        len(np.array(y)[train]) - sum(np.array(y)[train]),
        len(np.array(y)[test]) - sum(np.array(y)[test]),
        len(np.array(y)[validate])- sum(np.array(y)[validate]),
       ]
set_sizes["sizes"] = size
# set_sizes.to_csv("data_set_and_label_sizes")

In [4]:
set_sizes

       class                   task    data_set   sizes
0   positive      relevance_scoring       train   126.0
1   positive      relevance_scoring        test    38.0
2   positive      relevance_scoring  validation     NaN
3   positive    key_date_extraction       train    82.0
4   positive    key_date_extraction        test    27.0
5   positive    key_date_extraction  validation     NaN
6   positive   key_count_extraction       train   257.0
7   positive   key_count_extraction        test    98.0
8   positive   key_count_extraction  validation     NaN
9   positive  relevance_scoring_CNN       train    67.0
10  positive  relevance_scoring_CNN        test    42.0
11  positive  relevance_scoring_CNN  validation    55.0
12  negative      relevance_scoring       train  2301.0
13  negative      relevance_scoring        test   771.0
14  negative      relevance_scoring  validation     NaN
15  negative    key_date_extraction       train   161.0
16  negative    key_date_extraction        test    54.0
17  negative    key_date_extraction  validation     NaN
18  negative   key_count_extraction       train  2629.0
19  negative   key_count_extraction        test   865.0
20  negative   key_count_extraction  validation     NaN
21  negative  relevance_scoring_CNN       train  1874.0
22  negative  relevance_scoring_CNN        test   606.0
23  negative  relevance_scoring_CNN  validation   592.0